# -*- coding: utf-8 -*-
"""데이터 과학 7조 텀프로젝트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VkUaGaSEHnOS3f3d8bYKhIv23uVCzuAI
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
import platform
import platform
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

plt.rc('font', family='NanumBarunGothic')

df1 = pd.read_csv('/content/7월 이용.csv')
df2 = pd.read_csv('/content/7월 총.csv')

x = df1["동.읍.면"]
y1 = df1["이용횟수"]
y2 = df2["총요금"]

fig, ax1 = plt.subplots()
ax1.margins(x=0)
ax1.bar(x, y1, label = "배달 수")
ax1.set_xlabel('동.읍.면')
ax1.set_ylabel('이용횟수')

ax2 = ax1.twinx()
ax2.plot(x, y2, color = 'red', label = "총 금액")
ax2.set_ylabel("총 금액 (단위:천만원)")

ax = plt.gca()

current_values = ax1.get_yticks()

plt.title("순천시 7월 배달 이용률", fontsize = 15)

fig.autofmt_xdate(rotation = 90)
ax1.legend(loc=(0.01,1.1))
ax2.legend(loc=(0.01,1.02))

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
import platform
import platform
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

plt.rc('font', family='NanumBarunGothic')

df1 = pd.read_csv('/content/8월 이용.csv')
df2 = pd.read_csv('/content/8월 총.csv')

x = df1["동.읍.면"]
y1 = df1["이용횟수"]
y2 = df2["총요금"]

fig, ax1 = plt.subplots()
ax1.margins(x=0)
ax1.bar(x, y1, label = "배달 수")
ax1.set_xlabel('동.읍.면')
ax1.set_ylabel('이용횟수')

ax2 = ax1.twinx()
ax2.plot(x, y2, color = 'red', label = "총 금액")
ax2.set_ylabel("총 금액 (단위:천만원)")

ax = plt.gca()

current_values = ax1.get_yticks()

plt.title("순천시 8월 배달 이용률", fontsize = 15)

fig.autofmt_xdate(rotation = 90)
ax1.legend(loc=(0.01,1.1))
ax2.legend(loc=(0.01,1.02))

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
import platform
import platform
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

plt.rc('font', family='NanumBarunGothic')

df1 = pd.read_csv('/content/9월 이용.csv')
df2 = pd.read_csv('/content/9월 총.csv')

x = df1["동.읍.면"]
y1 = df1["이용횟수"]
y2 = df2["총요금"]

fig, ax1 = plt.subplots()
ax1.margins(x=0)
ax1.bar(x, y1, label = "배달 수")
ax1.set_xlabel('동.읍.면')
ax1.set_ylabel('이용횟수')

ax2 = ax1.twinx()
ax2.plot(x, y2, color = 'red', label = "총 금액")
ax2.set_ylabel("총 금액 (단위:천만원)")

ax = plt.gca()

current_values = ax1.get_yticks()

plt.title("순천시 9월 배달 이용률", fontsize = 15)

fig.autofmt_xdate(rotation = 90)
ax1.legend(loc=(0.01,1.1))
ax2.legend(loc=(0.01,1.02))

plt.show()